# Generated by Django 6.0.7 on 2026-07-29 11:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('notification_type', models.CharField(choices=[('INFO', "Ma'lumot"), ('WARNING', 'Ogohlantirish'), ('ERROR', 'Xato'), ('SUCCESS', 'Muvaffaqiyat'), ('TASK', 'Topshiriq'), ('DEADLINE', 'Muddat'), ('SYSTEM', 'Tizim')], default='INFO', max_length=20, verbose_name='Tur')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqt")),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Havola')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications_enabled', models.BooleanField(default=True, verbose_name='Email bildirishnomalari')),
                ('telegram_notifications_enabled', models.BooleanField(default=True, verbose_name='Telegram bildirishnomalari')),
                ('push_notifications_enabled', models.BooleanField(default=False, verbose_name='Push bildirishnomalari')),
                ('new_task_notifications_enabled', models.BooleanField(default=True, verbose_name='Yangi topshiriq bildirishnomalari')),
                ('deadline_reminders_enabled', models.BooleanField(default=True, verbose_name='Muddat eslatmalari')),
            ],
            options={
                'verbose_name': 'Bildirishnoma sozlamasi',
                'verbose_name_plural': 'Bildirishnoma sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField(unique=True, verbose_name='Push endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='P256DH kalit')),
                ('auth', models.CharField(max_length=255, verbose_name='Auth kalit')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='Brauzer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi muvaffaqiyatli yuborish')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Oxirgi xato')),
            ],
            options={
                'verbose_name': 'Push obuna',
                'verbose_name_plural': 'Push obunalar',
                'ordering': ['-updated_at'],
            },
        ),
    ]
