# Generated by Django 5.2.10 on 2026-01-22 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('notification_type', models.CharField(choices=[('INFO', "Ma'lumot"), ('WARNING', 'Ogohlantirish'), ('ERROR', 'Xato'), ('SUCCESS', 'Muvaffaqiyat'), ('TASK', 'Topshiriq'), ('DEADLINE', 'Muddat'), ('SYSTEM', 'Tizim')], default='INFO', max_length=20, verbose_name='Tur')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqt")),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Havola')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
