# Generated by Django 5.2.10 on 2026-04-06 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField(unique=True, verbose_name='Push endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='P256DH kalit')),
                ('auth', models.CharField(max_length=255, verbose_name='Auth kalit')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='Brauzer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi muvaffaqiyatli yuborish')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Oxirgi xato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Push obuna',
                'verbose_name_plural': 'Push obunalar',
                'ordering': ['-updated_at'],
            },
        ),
    ]
