# Generated by Django 5.2.10 on 2026-04-06 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications_enabled', models.BooleanField(default=True, verbose_name='Email bildirishnomalari')),
                ('telegram_notifications_enabled', models.BooleanField(default=True, verbose_name='Telegram bildirishnomalari')),
                ('push_notifications_enabled', models.BooleanField(default=False, verbose_name='Push bildirishnomalari')),
                ('new_task_notifications_enabled', models.BooleanField(default=True, verbose_name='Yangi topshiriq bildirishnomalari')),
                ('deadline_reminders_enabled', models.BooleanField(default=True, verbose_name='Muddat eslatmalari')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma sozlamasi',
                'verbose_name_plural': 'Bildirishnoma sozlamalari',
            },
        ),
    ]
