# Generated by Django 6.0.7 on 2026-07-29 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('summary', models.TextField(blank=True, verbose_name='Qisqa tavsif')),
                ('category', models.CharField(choices=[('MAHALLIY', 'Mahalliy loyiha'), ('XALQARO', 'Xalqaro loyiha'), ('DRIVER', 'Driver loyiha')], max_length=20, verbose_name='Kategoriya')),
                ('status', models.CharField(choices=[('REJA', 'Rejada'), ('TASDIQLANGAN', 'Tasdiqlangan'), ('IJRODA', 'Ijroda'), ('MONITORING', 'Monitoring'), ('YAKUNLANGAN', 'Yakunlangan')], default='REJA', max_length=20, verbose_name='Holati')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Progress foizi')),
                ('budget', models.CharField(blank=True, max_length=120, verbose_name='Byudjet/qiymat')),
                ('owner', models.CharField(blank=True, max_length=180, verbose_name="Mas'ul bo'lim")),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Yakun sanasi')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['category', 'sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Loyiha kommentariyasi',
                'verbose_name_plural': 'Loyiha kommentariyalari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATED', 'Yaratildi'), ('UPDATED', 'Yangilandi'), ('STATUS_CHANGED', "Holati o'zgardi"), ('PROGRESS_CHANGED', 'Progress yangilandi'), ('DELETED', "O'chirildi")], max_length=30, verbose_name='Amal turi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Qo‘shimcha ma’lumot')),
            ],
            options={
                'verbose_name': 'Loyiha tarixi',
                'verbose_name_plural': 'Loyiha tarixlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='projects/attachments/%Y/%m/', verbose_name='Fayl')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Fayl nomi')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Loyiha fayli',
                'verbose_name_plural': 'Loyiha fayllari',
                'ordering': ['-created_at'],
            },
        ),
    ]
