# Generated by Django 6.0.7 on 2026-07-29 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('total_users', models.PositiveIntegerField(default=0, verbose_name='Jami foydalanuvchilar')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='Faol foydalanuvchilar')),
                ('new_users', models.PositiveIntegerField(default=0, verbose_name='Yangi foydalanuvchilar')),
                ('total_organizations', models.PositiveIntegerField(default=0, verbose_name='Jami tashkilotlar')),
                ('total_tasks', models.PositiveIntegerField(default=0, verbose_name='Jami topshiriqlar')),
                ('new_tasks', models.PositiveIntegerField(default=0, verbose_name='Yangi topshiriqlar')),
                ('completed_tasks', models.PositiveIntegerField(default=0, verbose_name='Bajarilgan topshiriqlar')),
                ('overdue_tasks', models.PositiveIntegerField(default=0, verbose_name='Kechikkan topshiriqlar')),
                ('average_completion_time', models.FloatField(default=0, verbose_name="O'rtacha bajarilish vaqti")),
                ('system_rating', models.FloatField(default=0, verbose_name='Tizim reytingi')),
            ],
            options={
                'verbose_name': 'Dashboard snapshot',
                'verbose_name_plural': 'Dashboard snapshotlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Sana')),
                ('total_tasks', models.PositiveIntegerField(default=0, verbose_name='Jami topshiriqlar')),
                ('new_tasks', models.PositiveIntegerField(default=0, verbose_name='Yangi topshiriqlar')),
                ('in_progress_tasks', models.PositiveIntegerField(default=0, verbose_name='Ijrodagi topshiriqlar')),
                ('completed_tasks', models.PositiveIntegerField(default=0, verbose_name='Bajarilgan topshiriqlar')),
                ('overdue_tasks', models.PositiveIntegerField(default=0, verbose_name='Kechikkan topshiriqlar')),
                ('average_completion_time', models.FloatField(default=0, verbose_name="O'rtacha bajarilish vaqti (kun)")),
                ('on_time_completion_rate', models.FloatField(default=0, verbose_name="O'z vaqtida bajarilish foizi")),
                ('rating', models.FloatField(default=0, verbose_name='Reyting')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='organizations.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Tashkilot statistikasi',
                'verbose_name_plural': 'Tashkilot statistikalari',
                'ordering': ['-date'],
                'unique_together': {('organization', 'date')},
            },
        ),
    ]
