# Generated by Django 5.2.10 on 2026-01-22 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineExtensionRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_deadline', models.DateTimeField(verbose_name='Hozirgi muddat')),
                ('requested_deadline', models.DateTimeField(verbose_name="So'ralgan muddat")),
                ('reason', models.TextField(verbose_name='Sabab')),
                ('status', models.CharField(choices=[('KUTILMOQDA', 'Kutilmoqda'), ('TASDIQLANDI', 'Tasdiqlandi'), ('RAD_ETILDI', 'Rad etildi')], default='KUTILMOQDA', max_length=20, verbose_name='Holat')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqt")),
                ('review_comment', models.TextField(blank=True, verbose_name="Ko'rib chiqish izohi")),
            ],
            options={
                'verbose_name': "Muddat uzaytirish so'rovi",
                'verbose_name_plural': "Muddat uzaytirish so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('priority', models.CharField(choices=[('ODDIY', 'Oddiy'), ('MUHIM', 'Muhim'), ('SHOSHILINCH', 'Shoshilinch'), ('MUHIM_SHOSHILINCH', 'Muhim va shoshilinch')], default='ODDIY', max_length=20, verbose_name='Ustuvorlik')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategoriya')),
                ('status', models.CharField(choices=[('YANGI', 'Yangi'), ('IJRODA', 'Ijroda'), ('BAJARILDI', 'Bajarildi'), ('QAYTA_IJROGA_YUBORILDI', 'Qayta ijroga yuborildi'), ('MUDDATI_KECH', 'Muddati kechikkan'), ('BAJARILMADI', 'Bajarilmadi'), ('NAZORATDAN_YECHILDI', 'Nazoratdan yechildi')], default='YANGI', max_length=30, verbose_name='Holat')),
                ('deadline', models.DateTimeField(verbose_name='Muddat')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqt')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Uzunlik')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/', verbose_name='Fayl')),
                ('file_name', models.CharField(max_length=255, verbose_name='Fayl nomi')),
                ('file_type', models.CharField(choices=[('DOCUMENT', 'Hujjat'), ('IMAGE', 'Rasm'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('OTHER', 'Boshqa')], default='DOCUMENT', max_length=20, verbose_name='Fayl turi')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Fayl hajmi (bayt)')),
            ],
            options={
                'verbose_name': 'Topshiriq ilovasi',
                'verbose_name_plural': 'Topshiriq ilovalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('IJROGA_OLINDI', 'Ijroga olindi'), ('HISOBOT_TOPSHIRILDI', 'Hisobot topshirildi'), ('QAYTA_YUBORILDI', 'Qayta yuborildi'), ('NAZORATDAN_YECHILDI', 'Nazoratdan yechildi'), ('MUDDAT_UZAYTIRISH_SOROVI', "Muddat uzaytirish so'rovi"), ('MUDDAT_UZAYTIRILDI', 'Muddat uzaytirildi'), ('IZOH_QOSHILDI', "Izoh qo'shildi"), ('FAYL_YUKLANDI', 'Fayl yuklandi')], max_length=30, verbose_name='Amal turi')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('old_status', models.CharField(blank=True, max_length=30, verbose_name='Eski holat')),
                ('new_status', models.CharField(blank=True, max_length=30, verbose_name='Yangi holat')),
            ],
            options={
                'verbose_name': 'Topshiriq ijrosi',
                'verbose_name_plural': 'Topshiriq ijrolari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('TEXT', 'Matn'), ('FILE', 'Fayl'), ('AUDIO', 'Audio'), ('SYSTEM', 'Tizim xabari')], default='TEXT', max_length=20, verbose_name='Xabar turi')),
                ('content', models.TextField(verbose_name='Mazmun')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
            ],
            options={
                'verbose_name': 'Topshiriq xabari',
                'verbose_name_plural': 'Topshiriq xabarlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskOrganization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('YANGI', 'Yangi'), ('IJRODA', 'Ijroda'), ('BAJARILDI', 'Bajarildi'), ('QAYTA_IJROGA_YUBORILDI', 'Qayta ijroga yuborildi'), ('MUDDATI_KECH', 'Muddati kechikkan'), ('BAJARILMADI', 'Bajarilmadi'), ('NAZORATDAN_YECHILDI', 'Nazoratdan yechildi')], default='YANGI', max_length=30, verbose_name='Holat')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
            ],
            options={
                'verbose_name': 'Topshiriq biriktirilishi',
                'verbose_name_plural': 'Topshiriq biriktirilishlari',
            },
        ),
    ]
