# Generated by Django 6.0.7 on 2026-07-29 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlineextensionrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extension_requests', to=settings.AUTH_USER_MODEL, verbose_name="So'rov yuborgan"),
        ),
        migrations.AddField(
            model_name='deadlineextensionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_extensions', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqqan"),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='assigned_deputies',
            field=models.ManyToManyField(blank=True, related_name='deputy_recurring_tasks', to=settings.AUTH_USER_MODEL, verbose_name="Biriktirilgan hokim o'rinbosarlari"),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='recurring_tasks', to='organizations.organization', verbose_name='Tayinlangan tashkilotlar'),
        ),
        migrations.AddField(
            model_name='recurringtaskhistory',
            name='recurring_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.recurringtask', verbose_name='Takrorlanuvchi topshiriq'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_deputies',
            field=models.ManyToManyField(blank=True, related_name='deputy_tasks', to=settings.AUTH_USER_MODEL, verbose_name="Biriktirilgan hokim o'rinbosarlari"),
        ),
        migrations.AddField(
            model_name='task',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Yopgan'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='tasks.recurringtask', verbose_name='Takrorlanuvchi topshiriq'),
        ),
        migrations.AddField(
            model_name='recurringtaskhistory',
            name='created_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_source', to='tasks.task', verbose_name='Yaratilgan topshiriq'),
        ),
        migrations.AddField(
            model_name='deadlineextensionrequest',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='tasks.task', verbose_name='Topshiriq'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='Topshiriq'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='executed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_executions', to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tasks.task', verbose_name='Topshiriq'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.taskexecution', verbose_name='Ijro'),
        ),
        migrations.AddField(
            model_name='taskmessage',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='tasks.taskattachment', verbose_name='Ilova'),
        ),
        migrations.AddField(
            model_name='taskmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_task_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi'),
        ),
        migrations.AddField(
            model_name='taskmessage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tasks.task', verbose_name='Topshiriq'),
        ),
        migrations.AddField(
            model_name='taskorganization',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ijrochi'),
        ),
        migrations.AddField(
            model_name='taskorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='organizations.organization', verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='taskorganization',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_organizations', to='tasks.task', verbose_name='Topshiriq'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='task_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tasks.taskorganization', verbose_name='Tashkilot biriktirilishi'),
        ),
        migrations.AddField(
            model_name='deadlineextensionrequest',
            name='task_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='tasks.taskorganization', verbose_name='Tashkilot biriktirilishi'),
        ),
        migrations.AlterUniqueTogether(
            name='taskorganization',
            unique_together={('task', 'organization')},
        ),
    ]
