# Generated by Django 5.2.10 on 2026-01-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('PAST', 'Muhim emas va shoshilinch emas'), ('ODDIY', 'Shoshilinch, lekin muhim emas'), ('YUQORI', 'Muhim, lekin shoshilinch emas'), ('FAVQULODDA', 'Muhim va shoshilinch')], default='ODDIY', max_length=20, verbose_name='Ustuvorlik'),
        ),
    ]
