# Generated by Django 5.2.10 on 2026-02-01 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0004_alter_task_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('MANUAL', "Qo'lda yaratilgan"), ('RECURRING', 'Takrorlanuvchi'), ('AI', 'AI tomonidan'), ('TELEGRAM', 'Telegram bot')], default='MANUAL', max_length=20, verbose_name='Manba'),
        ),
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Topshiriq sarlavhasi')),
                ('description', models.TextField(verbose_name='Topshiriq tavsifi')),
                ('frequency', models.CharField(choices=[('DAILY', 'Har kuni'), ('WEEKLY', 'Har hafta'), ('BIWEEKLY', 'Ikki haftada bir'), ('MONTHLY', 'Har oy'), ('QUARTERLY', 'Har chorakda'), ('YEARLY', 'Har yili'), ('CUSTOM', 'Maxsus (cron)')], default='MONTHLY', max_length=20, verbose_name='Takrorlanish chastotasi')),
                ('cron_expression', models.CharField(blank=True, default='', help_text='Maxsus takrorlanish uchun cron formati', max_length=100, verbose_name='Cron ifodasi')),
                ('cron_description', models.CharField(blank=True, default='', max_length=255, verbose_name='Cron tavsifi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('next_run_date', models.DateTimeField(blank=True, null=True, verbose_name='Keyingi ishga tushish')),
                ('last_run_date', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi ishga tushish')),
                ('priority', models.CharField(choices=[('PAST', 'Muhim emas va shoshilinch emas'), ('ODDIY', 'Shoshilinch, lekin muhim emas'), ('YUQORI', 'Muhim, lekin shoshilinch emas'), ('FAVQULODDA', 'Muhim va shoshilinch')], default='ODDIY', max_length=20, verbose_name='Muhimlik darajasi')),
                ('deadline_days', models.PositiveIntegerField(default=7, verbose_name='Muddat (kun)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('PAUSED', "To'xtatilgan"), ('COMPLETED', 'Yakunlangan'), ('CANCELLED', 'Bekor qilingan')], default='ACTIVE', max_length=20, verbose_name='Holat')),
                ('total_created', models.PositiveIntegerField(default=0, verbose_name='Jami yaratilgan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('organizations', models.ManyToManyField(blank=True, related_name='recurring_tasks', to='organizations.organization', verbose_name='Tayinlangan tashkilotlar')),
            ],
            options={
                'verbose_name': 'Takrorlanuvchi topshiriq',
                'verbose_name_plural': 'Takrorlanuvchi topshiriqlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='tasks.recurringtask', verbose_name='Takrorlanuvchi topshiriq'),
        ),
        migrations.CreateModel(
            name='RecurringTaskHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField(verbose_name='Rejalashtirilgan sana')),
                ('created_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_source', to='tasks.task', verbose_name='Yaratilgan topshiriq')),
                ('recurring_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.recurringtask', verbose_name='Takrorlanuvchi topshiriq')),
            ],
            options={
                'verbose_name': 'Takrorlanuvchi topshiriq tarixi',
                'verbose_name_plural': 'Takrorlanuvchi topshiriq tarixlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
