# Generated by Django 6.0.7 on 2026-07-29 11:25

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('photo', 'Rasm'), ('video', 'Video'), ('audio', 'Audio'), ('voice', 'Ovozli xabar'), ('document', 'Hujjat'), ('video_note', 'Video xabar')], max_length=20, verbose_name='Fayl turi')),
                ('telegram_file_id', models.CharField(max_length=200, verbose_name='Telegram fayl ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='appeals/attachments/%Y/%m/', verbose_name='Fayl')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='Fayl nomi')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Fayl hajmi (bayt)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Murojaat ilovasi',
                'verbose_name_plural': 'Murojaat ilovalari',
            },
        ),
        migrations.CreateModel(
            name='AppealMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_admin', models.BooleanField(default=False, verbose_name='Admindan')),
                ('text', models.TextField(verbose_name='Xabar matni')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='AI tomonidan yaratilgan')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram xabar ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Murojaat xabari',
                'verbose_name_plural': 'Murojaat xabarlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppealReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi o'qilgan vaqt")),
            ],
            options={
                'verbose_name': "Murojaat o'qilgan holati",
                'verbose_name_plural': "Murojaat o'qilgan holatlari",
            },
        ),
        migrations.CreateModel(
            name='AppealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ruscha)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Inglizcha)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('icon', models.CharField(default='📝', max_length=10, verbose_name='Emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Murojaat turi',
                'verbose_name_plural': 'Murojaat turlari',
                'ordering': ['order', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Telegram username')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name="To'liq ism")),
                ('is_super_admin', models.BooleanField(default=False, verbose_name='Super admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('can_approve_appeals', models.BooleanField(default=True, verbose_name='Murojaatlarni tasdiqlash')),
                ('can_respond_appeals', models.BooleanField(default=True, verbose_name='Murojaatlarga javob berish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot admin',
                'verbose_name_plural': 'Bot adminlar',
            },
        ),
        migrations.CreateModel(
            name='BotRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ruscha)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Inglizcha)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
                'ordering': ['order', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text="Telegram BotFather'dan olingan token", max_length=100, verbose_name='Bot Token')),
                ('bot_username', models.CharField(blank=True, max_length=100, verbose_name='Bot username')),
                ('is_active', models.BooleanField(default=False, verbose_name='Bot faolmi')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='Webhook URL')),
                ('use_webhook', models.BooleanField(default=False, verbose_name='Webhook ishlatish')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=128, verbose_name='Webhook secret')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI (GPT)'), ('anthropic', 'Anthropic (Claude)'), ('disabled', "O'chirilgan")], default='disabled', max_length=20, verbose_name='AI provayder')),
                ('ai_api_key', models.CharField(blank=True, max_length=200, verbose_name='AI API kaliti')),
                ('ai_model', models.CharField(default='gpt-4o-mini', max_length=50, verbose_name='AI modeli')),
                ('auto_response_enabled', models.BooleanField(default=True, help_text='Admin javob bermasa AI avtomatik javob beradi', verbose_name='AI avtomatik javob')),
                ('auto_response_timeout_minutes', models.PositiveIntegerField(default=5, help_text="Admin javob berish uchun kutish vaqti (daqiqada). O'tgandan so'ng AI javob beradi.", verbose_name='Kutish vaqti (daqiqa)')),
                ('welcome_message_uz', models.TextField(default='🏛 Xatirchi hokimligiga xush kelibsiz!\n\nBu bot orqali siz murojaatlaringizni yuborishingiz mumkin.', verbose_name="Salomlashish xabari (O'zbekcha)")),
                ('welcome_message_ru', models.TextField(default='🏛 Добро пожаловать в хокимият Хатырчи!\n\nЧерез этого бота вы можете отправлять свои обращения.', verbose_name='Salomlashish xabari (Ruscha)')),
                ('welcome_message_en', models.TextField(default='🏛 Welcome to Hatirchi Hokimiyat!\n\nYou can send your appeals through this bot.', verbose_name='Salomlashish xabari (Inglizcha)')),
                ('about_text_uz', models.TextField(default='🏛 <b>Hatirchi tumani Hokimiyati</b>\n\n📍 Manzil: Xatirchi tumani, Mustaqillik ko‘chasi 34-uy\n\n📞 Telefon: +99879 544-40-10\n📧 Email: xatirchi@nv.uz\n🌐 Sayt: https://gov.uz/uz/xatirchi\n\n🕐 Ish vaqti: Dushanba - Juma, 9:00 - 18:00\n\nBu bot orqali siz murojaatlar yuborishingiz va ularning holatini kuzatishingiz mumkin.', verbose_name="Biz haqimizda matni (O'zbekcha)")),
                ('about_text_ru', models.TextField(default='🏛 <b>Хокимият Хатырчинского района</b>\n\nЦифровая платформа для приема, рассмотрения и контроля обращений граждан.\n\n📍 Адрес: Хатырчинский район\n📞 Телефон: +998 XX XXX XX XX\n🌐 Платформа: ehokimiyat.uz\n\nПлатформа разработана компанией Aura group.', verbose_name='Biz haqimizda matni (Ruscha)')),
                ('about_text_en', models.TextField(default='🏛 <b>Hatirchi District Administration</b>\n\nA digital platform for receiving, reviewing, and monitoring citizen appeals.\n\n📍 Address: Hatirchi district\n📞 Phone: +998 XX XXX XX XX\n🌐 Platform: ehokimiyat.uz\n\nThe platform was developed by Aura group.', verbose_name='Biz haqimizda matni (Inglizcha)')),
                ('help_text_uz', models.TextField(default="❓ <b>Yordam</b>\n\n<b>Bot imkoniyatlari:</b>\n📝 Murojaat yuborish - Hokimiyatga shikoyat, taklif yoki savollar yuborish\n📋 Murojaatlarim - O'z murojaatlaringiz holatini kuzatish\n⚙️ Sozlamalar - Shaxsiy ma'lumotlarni tahrirlash\n\n<b>Buyruqlar:</b>\n/start - Botni qayta ishga tushirish\n/menu - Asosiy menyu\n/help - Yordam\n/settings - Sozlamalar\n\n<b>Muammo bo'lsa:</b>\n+99879 544-40-10 raqamiga qo'ng'iroq qiling.", verbose_name="Yordam matni (O'zbekcha)")),
                ('help_text_ru', models.TextField(default='❓ <b>Помощь</b>', verbose_name='Yordam matni (Ruscha)')),
                ('help_text_en', models.TextField(default='❓ <b>Help</b>', verbose_name='Yordam matni (Inglizcha)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot sozlamalari',
                'verbose_name_plural': 'Bot sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='TelegramAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('appeal_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Murojaat raqami')),
                ('citizen_name', models.CharField(blank=True, default='', max_length=200, verbose_name="Fuqaro F.I.Sh (qo'lda)")),
                ('citizen_phone', models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998[0-9]{9}$')], verbose_name="Telefon raqam (qo'lda)")),
                ('citizen_gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], default='', max_length=10, verbose_name="Jinsi (qo'lda)")),
                ('citizen_language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5, verbose_name="Til (qo'lda)")),
                ('text', models.TextField(verbose_name='Murojaat matni')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Kenglik (latitude)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Uzunlik (longitude)')),
                ('address', models.TextField(blank=True, default='', verbose_name='Manzil (ixtiyoriy)')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending_ai', 'AI tekshiruvida'), ('pending_review', 'Admin tekshiruvida'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('responded', 'Javob berilgan'), ('forwarded', 'Topshiriq sifatida kiritilgan'), ('resolved', 'Hal qilingan')], default='draft', max_length=20, verbose_name='Holat')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='medium', max_length=20, verbose_name='Muhimlik darajasi')),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Veb-sayt'), ('manual', "Qo'lda kiritilgan")], default='telegram', max_length=20, verbose_name='Manba')),
                ('ai_analysis', models.TextField(blank=True, default='', verbose_name='AI tahlili')),
                ('ai_score', models.IntegerField(default=0, verbose_name='AI ball')),
                ('ai_priority', models.CharField(blank=True, choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], max_length=20, null=True, verbose_name='AI aniqlagan muhimlik')),
                ('ai_response', models.TextField(blank=True, verbose_name='AI javobi')),
                ('ai_is_valid', models.BooleanField(default=True, verbose_name="AI: Murojaat to'g'ri")),
                ('ai_rejection_reason', models.TextField(blank=True, default='', null=True, verbose_name='AI rad etish sababi')),
                ('admin_response', models.TextField(blank=True, verbose_name='Admin javobi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqt")),
                ('admin_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Adminlarga xabar yuborilgan vaqt')),
                ('ai_auto_responded', models.BooleanField(default=False, verbose_name='AI avtomatik javob bergan')),
                ('forwarded_to_site', models.BooleanField(default=False, verbose_name='Topshiriq sifatida kiritilgan')),
                ('site_appeal_id', models.IntegerField(blank=True, null=True, verbose_name='Saytdagi murojaat ID')),
                ('site_task_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Saytdagi topshiriq ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Foydalanuvchi xizmatni baholashi', null=True, verbose_name='Baho (1-5)')),
                ('rating_comment', models.TextField(blank=True, default='', verbose_name='Baho izohi')),
                ('rated_at', models.DateTimeField(blank=True, null=True, verbose_name='Baholangan vaqt')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram murojaat',
                'verbose_name_plural': 'Telegram murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998[0-9]{9}$')], verbose_name='Telefon raqam')),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5, verbose_name='Til')),
                ('is_registered', models.BooleanField(default=False, verbose_name="Ro'yxatdan o'tgan")),
                ('registration_step', models.CharField(default='start', max_length=50, verbose_name="Ro'yxatdan o'tish bosqichi")),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('block_reason', models.TextField(blank=True, verbose_name='Bloklash sababi')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='Ogohlantirish soni')),
                ('last_warning_date', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi ogohlantirish sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchi',
                'verbose_name_plural': 'Telegram foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('state', models.CharField(default='start', max_length=100, verbose_name='Holat')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumotlar")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi holati',
                'verbose_name_plural': 'Foydalanuvchi holatlari',
            },
        ),
        migrations.CreateModel(
            name='AppealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ruscha)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Inglizcha)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('icon', models.CharField(default='📋', max_length=10, verbose_name='Emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('responsible_organizations', models.ManyToManyField(blank=True, related_name='responsible_appeal_categories', to='organizations.organization', verbose_name="Mas'ul tashkilotlar")),
            ],
            options={
                'verbose_name': 'Murojaat sohasi',
                'verbose_name_plural': 'Murojaat sohalari',
                'ordering': ['order', 'name_uz'],
            },
        ),
    ]
