# Generated by Django 5.2.10 on 2026-01-31 02:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ruscha)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Inglizcha)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('icon', models.CharField(default='📋', max_length=10, verbose_name='Emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Murojaat sohasi',
                'verbose_name_plural': 'Murojaat sohalari',
                'ordering': ['order', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='AppealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ruscha)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Inglizcha)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('icon', models.CharField(default='📝', max_length=10, verbose_name='Emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Murojaat turi',
                'verbose_name_plural': 'Murojaat turlari',
                'ordering': ['order', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='BotRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ruscha)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Inglizcha)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
                'ordering': ['order', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text="Telegram BotFather'dan olingan token", max_length=100, verbose_name='Bot Token')),
                ('bot_username', models.CharField(blank=True, max_length=100, verbose_name='Bot username')),
                ('is_active', models.BooleanField(default=False, verbose_name='Bot faolmi')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='Webhook URL')),
                ('use_webhook', models.BooleanField(default=False, verbose_name='Webhook ishlatish')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI (GPT)'), ('anthropic', 'Anthropic (Claude)'), ('disabled', "O'chirilgan")], default='disabled', max_length=20, verbose_name='AI provayder')),
                ('ai_api_key', models.CharField(blank=True, max_length=200, verbose_name='AI API kaliti')),
                ('ai_model', models.CharField(default='gpt-4o-mini', max_length=50, verbose_name='AI modeli')),
                ('welcome_message_uz', models.TextField(default='🏛 Xatirchi hokimligiga xush kelibsiz!\n\nBu bot orqali siz murojaatlaringizni yuborishingiz mumkin.', verbose_name="Salomlashish xabari (O'zbekcha)")),
                ('welcome_message_ru', models.TextField(default='🏛 Добро пожаловать в хокимият Хатырчи!\n\nЧерез этого бота вы можете отправлять свои обращения.', verbose_name='Salomlashish xabari (Ruscha)')),
                ('welcome_message_en', models.TextField(default='🏛 Welcome to Hatirchi Hokimiyat!\n\nYou can send your appeals through this bot.', verbose_name='Salomlashish xabari (Inglizcha)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot sozlamalari',
                'verbose_name_plural': 'Bot sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('state', models.CharField(default='start', max_length=100, verbose_name='Holat')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumotlar")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi holati',
                'verbose_name_plural': 'Foydalanuvchi holatlari',
            },
        ),
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Telegram username')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name="To'liq ism")),
                ('is_super_admin', models.BooleanField(default=False, verbose_name='Super admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('can_approve_appeals', models.BooleanField(default=True, verbose_name='Murojaatlarni tasdiqlash')),
                ('can_respond_appeals', models.BooleanField(default=True, verbose_name='Murojaatlarga javob berish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_admin_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Tizim foydalanuvchisi')),
            ],
            options={
                'verbose_name': 'Bot admin',
                'verbose_name_plural': 'Bot adminlar',
            },
        ),
        migrations.CreateModel(
            name='TelegramAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('appeal_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Murojaat raqami')),
                ('text', models.TextField(verbose_name='Murojaat matni')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending_ai', 'AI tekshiruvida'), ('pending_review', 'Admin tekshiruvida'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('responded', 'Javob berilgan'), ('forwarded', 'Saytga yuborilgan'), ('resolved', 'Hal qilingan')], default='draft', max_length=20, verbose_name='Holat')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='medium', max_length=20, verbose_name='Muhimlik darajasi')),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Veb-sayt'), ('manual', "Qo'lda kiritilgan")], default='telegram', max_length=20, verbose_name='Manba')),
                ('ai_analysis', models.JSONField(blank=True, null=True, verbose_name='AI tahlili')),
                ('ai_priority', models.CharField(blank=True, choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], max_length=20, null=True, verbose_name='AI aniqlagan muhimlik')),
                ('ai_response', models.TextField(blank=True, verbose_name='AI javobi')),
                ('ai_is_valid', models.BooleanField(default=True, verbose_name="AI: Murojaat to'g'ri")),
                ('ai_rejection_reason', models.TextField(blank=True, verbose_name='AI rad etish sababi')),
                ('admin_response', models.TextField(blank=True, verbose_name='Admin javobi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqt")),
                ('forwarded_to_site', models.BooleanField(default=False, verbose_name='Saytga yuborilgan')),
                ('site_appeal_id', models.IntegerField(blank=True, null=True, verbose_name='Saytdagi murojaat ID')),
                ('site_task_id', models.IntegerField(blank=True, null=True, verbose_name='Saytdagi topshiriq ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_category_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggested_appeals', to='telegram_bot.appealcategory', verbose_name='AI taklif qilgan soha')),
                ('appeal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='telegram_bot.appealtype', verbose_name='Murojaat turi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='telegram_bot.appealcategory', verbose_name='Murojaat sohasi')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to='telegram_bot.botadmin', verbose_name="Ko'rib chiqqan admin")),
            ],
            options={
                'verbose_name': 'Telegram murojaat',
                'verbose_name_plural': 'Telegram murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppealMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_admin', models.BooleanField(default=False, verbose_name='Admindan')),
                ('text', models.TextField(verbose_name='Xabar matni')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='AI tomonidan yaratilgan')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram xabar ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_bot.botadmin', verbose_name='Admin')),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram_bot.telegramappeal', verbose_name='Murojaat')),
            ],
            options={
                'verbose_name': 'Murojaat xabari',
                'verbose_name_plural': 'Murojaat xabarlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppealAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('photo', 'Rasm'), ('video', 'Video'), ('audio', 'Audio'), ('voice', 'Ovozli xabar'), ('document', 'Hujjat'), ('video_note', 'Video xabar')], max_length=20, verbose_name='Fayl turi')),
                ('telegram_file_id', models.CharField(max_length=200, verbose_name='Telegram fayl ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='appeals/attachments/%Y/%m/', verbose_name='Fayl')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='Fayl nomi')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Fayl hajmi (bayt)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='telegram_bot.telegramappeal', verbose_name='Murojaat')),
            ],
            options={
                'verbose_name': 'Murojaat ilovasi',
                'verbose_name_plural': 'Murojaat ilovalari',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998[0-9]{9}$')], verbose_name='Telefon raqam')),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5, verbose_name='Til')),
                ('is_registered', models.BooleanField(default=False, verbose_name="Ro'yxatdan o'tgan")),
                ('registration_step', models.CharField(default='start', max_length=50, verbose_name="Ro'yxatdan o'tish bosqichi")),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_users', to='telegram_bot.botregion', verbose_name='Hudud')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tizim foydalanuvchisi')),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchi',
                'verbose_name_plural': 'Telegram foydalanuvchilar',
            },
        ),
        migrations.AddField(
            model_name='telegramappeal',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='telegram_bot.telegramuser', verbose_name='Telegram foydalanuvchi'),
        ),
    ]
