# Generated by Django 5.2.10 on 2026-01-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramappeal',
            name='ai_score',
            field=models.IntegerField(default=0, verbose_name='AI ball'),
        ),
        migrations.AlterField(
            model_name='telegramappeal',
            name='ai_analysis',
            field=models.TextField(blank=True, default=1, verbose_name='AI tahlili'),
            preserve_default=False,
        ),
    ]
