# Generated by Django 6.0.7 on 2026-07-29 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('telegram_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appealmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='appealreadstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal_read_states', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='botadmin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_admin_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Tizim foydalanuvchisi'),
        ),
        migrations.AddField(
            model_name='appealmessage',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_bot.botadmin', verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='telegramappeal',
            name='ai_category_suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggested_appeals', to='telegram_bot.appealcategory', verbose_name='AI taklif qilgan soha'),
        ),
        migrations.AddField(
            model_name='telegramappeal',
            name='appeal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='telegram_bot.appealtype', verbose_name='Murojaat turi'),
        ),
        migrations.AddField(
            model_name='telegramappeal',
            name='assigned_organizations',
            field=models.ManyToManyField(blank=True, related_name='telegram_appeals', to='organizations.organization', verbose_name='Biriktirilgan tashkilotlar'),
        ),
        migrations.AddField(
            model_name='telegramappeal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='telegram_bot.appealcategory', verbose_name='Murojaat sohasi'),
        ),
        migrations.AddField(
            model_name='telegramappeal',
            name='citizen_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_appeals', to='telegram_bot.botregion', verbose_name="Hudud (qo'lda)"),
        ),
        migrations.AddField(
            model_name='telegramappeal',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_telegram_appeals', to=settings.AUTH_USER_MODEL, verbose_name="Qo'lda kiritgan foydalanuvchi"),
        ),
        migrations.AddField(
            model_name='telegramappeal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to='telegram_bot.botadmin', verbose_name="Ko'rib chiqqan admin"),
        ),
        migrations.AddField(
            model_name='appealreadstate',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='telegram_bot.telegramappeal', verbose_name='Murojaat'),
        ),
        migrations.AddField(
            model_name='appealmessage',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram_bot.telegramappeal', verbose_name='Murojaat'),
        ),
        migrations.AddField(
            model_name='appealattachment',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='telegram_bot.telegramappeal', verbose_name='Murojaat'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_users', to='telegram_bot.botregion', verbose_name='Hudud'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tizim foydalanuvchisi'),
        ),
        migrations.AddField(
            model_name='telegramappeal',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='telegram_bot.telegramuser', verbose_name='Telegram foydalanuvchi'),
        ),
        migrations.AlterUniqueTogether(
            name='appealreadstate',
            unique_together={('appeal', 'user')},
        ),
    ]
