# Generated by Django 5.2.10 on 2026-01-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_add_ai_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramappeal',
            name='ai_analysis',
            field=models.TextField(blank=True, default='', verbose_name='AI tahlili'),
        ),
    ]
