# Generated by Django 5.2.10 on 2026-01-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_add_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='block_reason',
            field=models.TextField(blank=True, verbose_name='Bloklash sababi'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_warning_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi ogohlantirish sanasi'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='warning_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ogohlantirish soni'),
        ),
    ]
