# Generated by Django 6.0.8 on 2026-09-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_appealmessage_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealattachment',
            name='telegram_file_path',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name="Telegram fayl yo'li (kesh)"),
        ),
        migrations.AddField(
            model_name='appealattachment',
            name='telegram_path_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fayl yo'li yangilangan vaqt"),
        ),
    ]
