# Generated by Django 5.2.10 on 2026-01-31 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_add_warning_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramappeal',
            name='ai_rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='AI rad etish sababi'),
        ),
    ]
