# Generated by Django 5.2.10 on 2026-02-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_fix_ai_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramappeal',
            name='ai_rejection_reason',
            field=models.TextField(blank=True, default='', null=True, verbose_name='AI rad etish sababi'),
        ),
        migrations.AlterField(
            model_name='telegramappeal',
            name='forwarded_to_site',
            field=models.BooleanField(default=False, verbose_name='Topshiriq sifatida kiritilgan'),
        ),
        migrations.AlterField(
            model_name='telegramappeal',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('pending_ai', 'AI tekshiruvida'), ('pending_review', 'Admin tekshiruvida'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('responded', 'Javob berilgan'), ('forwarded', 'Topshiriq sifatida kiritilgan'), ('resolved', 'Hal qilingan')], default='draft', max_length=20, verbose_name='Holat'),
        ),
    ]
