# Generated by Django 5.2.10 on 2026-02-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_fix_ai_rejection_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramappeal',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqt'),
        ),
        migrations.AddField(
            model_name='telegramappeal',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Baholangan vaqt'),
        ),
        migrations.AddField(
            model_name='telegramappeal',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Foydalanuvchi xizmatni baholashi', null=True, verbose_name='Baho (1-5)'),
        ),
        migrations.AddField(
            model_name='telegramappeal',
            name='rating_comment',
            field=models.TextField(blank=True, default='', verbose_name='Baho izohi'),
        ),
    ]
