# Generated by Django - Default data for Telegram Bot
from django.db import migrations


def add_default_appeal_types(apps, schema_editor):
    """Default murojaat turlarini qo'shish"""
    AppealType = apps.get_model('telegram_bot', 'AppealType')
    
    appeal_types = [
        {
            "name_uz": "Ariza",
            "name_ru": "Заявление",
            "name_en": "Application",
            "code": "application",
            "icon": "📋",
            "order": 1
        },
        {
            "name_uz": "Shikoyat",
            "name_ru": "Жалоба",
            "name_en": "Complaint",
            "code": "complaint",
            "icon": "⚠️",
            "order": 2
        },
        {
            "name_uz": "Taklif",
            "name_ru": "Предложение",
            "name_en": "Suggestion",
            "code": "suggestion",
            "icon": "💡",
            "order": 3
        },
        {
            "name_uz": "So'rov",
            "name_ru": "Запрос",
            "name_en": "Request",
            "code": "request",
            "icon": "❓",
            "order": 4
        },
    ]
    
    for data in appeal_types:
        AppealType.objects.get_or_create(code=data['code'], defaults=data)


def add_default_categories(apps, schema_editor):
    """Default kategoriyalarni qo'shish"""
    AppealCategory = apps.get_model('telegram_bot', 'AppealCategory')
    
    categories = [
        {"name_uz": "Ta'lim va fan", "name_ru": "Образование и наука", "name_en": "Education", "code": "education", "icon": "📚", "order": 1},
        {"name_uz": "Sog'liqni saqlash", "name_ru": "Здравоохранение", "name_en": "Healthcare", "code": "healthcare", "icon": "🏥", "order": 2},
        {"name_uz": "Kommunal xizmatlar", "name_ru": "Коммунальные услуги", "name_en": "Utilities", "code": "utilities", "icon": "🔧", "order": 3},
        {"name_uz": "Yo'l va transport", "name_ru": "Дороги и транспорт", "name_en": "Roads & Transport", "code": "transport", "icon": "🚗", "order": 4},
        {"name_uz": "Ijtimoiy himoya", "name_ru": "Социальная защита", "name_en": "Social Protection", "code": "social", "icon": "🤝", "order": 5},
        {"name_uz": "Qurilish va arxitektura", "name_ru": "Строительство и архитектура", "name_en": "Construction", "code": "construction", "icon": "🏗️", "order": 6},
        {"name_uz": "Yer masalalari", "name_ru": "Земельные вопросы", "name_en": "Land Issues", "code": "land", "icon": "🏞️", "order": 7},
        {"name_uz": "Ekologiya", "name_ru": "Экология", "name_en": "Ecology", "code": "ecology", "icon": "🌿", "order": 8},
        {"name_uz": "Xavfsizlik", "name_ru": "Безопасность", "name_en": "Security", "code": "security", "icon": "🛡️", "order": 9},
        {"name_uz": "Boshqa", "name_ru": "Другое", "name_en": "Other", "code": "other", "icon": "📁", "order": 10},
    ]
    
    for data in categories:
        AppealCategory.objects.get_or_create(code=data['code'], defaults=data)


def add_default_regions(apps, schema_editor):
    """Default hududlarni qo'shish"""
    BotRegion = apps.get_model('telegram_bot', 'BotRegion')
    
    regions = [
        {"name_uz": "Hatirchi shaharchasi", "name_ru": "г. Хатирчи", "name_en": "Hatirchi town", "code": "hatirchi", "order": 1},
        {"name_uz": "Gulzor MFY", "name_ru": "МСГ Гулзор", "name_en": "Gulzor MFY", "code": "gulzor", "order": 2},
        {"name_uz": "Bog'ishamol MFY", "name_ru": "МСГ Богишамол", "name_en": "Bogishamol MFY", "code": "bogishamol", "order": 3},
        {"name_uz": "Yangi hayot MFY", "name_ru": "МСГ Янги хаёт", "name_en": "Yangi hayot MFY", "code": "yangihayot", "order": 4},
        {"name_uz": "Mustaqillik MFY", "name_ru": "МСГ Мустакиллик", "name_en": "Mustaqillik MFY", "code": "mustaqillik", "order": 5},
        {"name_uz": "Navbahor MFY", "name_ru": "МСГ Навбахор", "name_en": "Navbahor MFY", "code": "navbahor", "order": 6},
        {"name_uz": "Tinchlik MFY", "name_ru": "МСГ Тинчлик", "name_en": "Tinchlik MFY", "code": "tinchlik", "order": 7},
        {"name_uz": "Oqtepa MFY", "name_ru": "МСГ Октепа", "name_en": "Oqtepa MFY", "code": "oqtepa", "order": 8},
    ]
    
    for data in regions:
        BotRegion.objects.get_or_create(code=data['code'], defaults=data)


def remove_default_data(apps, schema_editor):
    """Rollback - default ma'lumotlarni o'chirish"""
    AppealType = apps.get_model('telegram_bot', 'AppealType')
    AppealCategory = apps.get_model('telegram_bot', 'AppealCategory')
    BotRegion = apps.get_model('telegram_bot', 'BotRegion')
    
    AppealType.objects.filter(code__in=['application', 'complaint', 'suggestion', 'request']).delete()
    AppealCategory.objects.filter(code__in=['education', 'healthcare', 'utilities', 'transport', 'social', 'construction', 'land', 'ecology', 'security', 'other']).delete()
    BotRegion.objects.filter(code__in=['hatirchi', 'gulzor', 'bogishamol', 'yangihayot', 'mustaqillik', 'navbahor', 'tinchlik', 'oqtepa']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_add_rating_fields'),
    ]

    operations = [
        migrations.RunPython(add_default_appeal_types, remove_default_data),
        migrations.RunPython(add_default_categories, migrations.RunPython.noop),
        migrations.RunPython(add_default_regions, migrations.RunPython.noop),
    ]
