# Generated by Django 6.0.3 on 2026-03-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0017_botsettings_help_texts"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramappeal",
            name="address",
            field=models.TextField(
                blank=True, default="", verbose_name="Manzil (ixtiyoriy)"
            ),
        ),
        migrations.AddField(
            model_name="telegramappeal",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="Kenglik (latitude)",
            ),
        ),
        migrations.AddField(
            model_name="telegramappeal",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="Uzunlik (longitude)",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="about_text_uz",
            field=models.TextField(
                default="🏛 <b>Hatirchi tumani Hokimiyati</b>\n\n📍 Manzil: Xatirchi tumani, Mustaqillik ko‘chasi 34-uy\n\n📞 Telefon: +99879 544-40-10\n📧 Email: xatirchi@nv.uz\n🌐 Sayt: https://gov.uz/uz/xatirchi\n\n🕐 Ish vaqti: Dushanba - Juma, 9:00 - 18:00\n\nBu bot orqali siz murojaatlar yuborishingiz va ularning holatini kuzatishingiz mumkin.",
                verbose_name="Biz haqimizda matni (O'zbekcha)",
            ),
        ),
    ]
