# Generated by Django 6.0.3 on 2026-03-27 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "telegram_bot",
            "0018_telegramappeal_address_telegramappeal_latitude_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppealReadState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Oxirgi o'qilgan vaqt"
                    ),
                ),
                (
                    "appeal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_states",
                        to="telegram_bot.telegramappeal",
                        verbose_name="Murojaat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeal_read_states",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Murojaat o'qilgan holati",
                "verbose_name_plural": "Murojaat o'qilgan holatlari",
                "unique_together": {("appeal", "user")},
            },
        ),
    ]
