# Generated by Django 5.2.10 on 2026-01-22 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('HOKIM', 'Hokim'), ('HOKIMLIK_MASUL', "Hokimlik mas'uli"), ('TASHKILOT_RAHBARI', 'Tashkilot rahbari'), ('TASHKILOT_MASUL', "Tashkilot mas'uli"), ('ADMIN', 'Administrator')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rollar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pnfl', models.CharField(db_index=True, max_length=14, unique=True, verbose_name='PNFL (JSHSHR)')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('HOKIM', 'Hokim'), ('HOKIMLIK_MASUL', "Hokimlik mas'uli"), ('TASHKILOT_RAHBARI', 'Tashkilot rahbari'), ('TASHKILOT_MASUL', "Tashkilot mas'uli"), ('ADMIN', 'Administrator')], max_length=20, verbose_name='Rol')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Lavozim')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('KUTILMOQDA', 'Kutilmoqda'), ('FAOL', 'Faol'), ('BLOKLANGAN', 'Bloklangan'), ('ARXIV', 'Arxiv')], default='KUTILMOQDA', max_length=20, verbose_name='Holat')),
                ('oneid_connected', models.BooleanField(default=False, verbose_name='OneID ulangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Faollashtirilgan vaqt')),
                ('first_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Birinchi kirish vaqti')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.organization', verbose_name='Tashkilot')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_role', models.CharField(max_length=20, verbose_name='Biriktirilgan rol')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirgan foydalanuvchi')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi biriktirmasi',
                'verbose_name_plural': 'Foydalanuvchi biriktirmalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
