# Generated by Django 6.0.7 on 2026-07-29 11:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('USER_CREATED', 'Foydalanuvchi yaratildi'), ('USER_UPDATED', 'Foydalanuvchi yangilandi'), ('USER_BLOCKED', 'Foydalanuvchi bloklandi'), ('USER_ARCHIVED', 'Foydalanuvchi arxivlandi'), ('USER_ACTIVATED', 'Foydalanuvchi faollashtirildi'), ('USER_LOGIN', 'Foydalanuvchi kirdi'), ('USER_LOGOUT', 'Foydalanuvchi chiqdi'), ('USER_LOGIN_FAILED', 'Kirish muvaffaqiyatsiz'), ('ORG_CREATED', 'Tashkilot yaratildi'), ('ORG_UPDATED', 'Tashkilot yangilandi'), ('ORG_DELETED', "Tashkilot o'chirildi"), ('TASK_CREATED', 'Topshiriq yaratildi'), ('TASK_UPDATED', 'Topshiriq yangilandi'), ('TASK_ACCEPTED', 'Topshiriq qabul qilindi'), ('TASK_COMPLETED', 'Topshiriq bajarildi'), ('TASK_REASSIGNED', 'Topshiriq qayta yuborildi'), ('TASK_CLOSED', 'Topshiriq yopildi'), ('TASK_OVERDUE', "Topshiriq muddati o'tdi"), ('REPORT_SUBMITTED', 'Hisobot topshirildi'), ('REPORT_REVIEWED', "Hisobot ko'rib chiqildi"), ('EXTENSION_REQUESTED', "Muddat uzaytirish so'raldi"), ('EXTENSION_APPROVED', 'Muddat uzaytirish tasdiqlandi'), ('EXTENSION_REJECTED', 'Muddat uzaytirish rad etildi'), ('SYSTEM_ERROR', 'Tizim xatosi'), ('DATA_EXPORT', "Ma'lumotlar eksport qilindi")], max_length=50, verbose_name='Amal')),
                ('entity_type', models.CharField(choices=[('USER', 'Foydalanuvchi'), ('ORGANIZATION', 'Tashkilot'), ('TASK', 'Topshiriq'), ('TASK_ORGANIZATION', 'Topshiriq biriktirilishi'), ('REPORT', 'Hisobot'), ('EXTENSION_REQUEST', "Muddat uzaytirish so'rovi"), ('NOTIFICATION', 'Bildirishnoma'), ('SYSTEM', 'Tizim')], max_length=30, verbose_name="Ob'yekt turi")),
                ('entity_id', models.CharField(blank=True, max_length=100, verbose_name="Ob'yekt ID")),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Eski qiymatlar')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Yangi qiymatlar')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit loglar',
                'ordering': ['-created_at'],
            },
        ),
    ]
