# Generated by Django 6.0.7 on 2026-07-29 11:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATE_RECURRING_TASK', 'Takrorlanuvchi topshiriq yaratish'), ('EXPORT_ANALYTICS', 'Analitika faylini yaratish'), ('CREATE_TASK', 'Topshiriq yaratish'), ('CLOSE_TASK', 'Topshiriqni yopish'), ('REMOVE_CONTROL', 'Nazoratdan yechish'), ('GENERATE_REPORT', 'Hisobot yaratish'), ('SEND_NOTIFICATION', 'Bildirishnoma yuborish'), ('CLOSE_APPEAL', 'Murojaatni yopish')], max_length=30, verbose_name='Harakat turi')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('IN_PROGRESS', 'Bajarilmoqda'), ('COMPLETED', 'Bajarildi'), ('FAILED', 'Xato'), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=20, verbose_name='Holat')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parametrlar')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Natija')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI harakat',
                'verbose_name_plural': 'AI harakatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Suhbat sarlavhasi')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('COMPLETED', 'Yakunlangan'), ('ARCHIVED', 'Arxivlangan')], default='ACTIVE', max_length=20, verbose_name='Holat')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Kontekst')),
                ('message_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'AI suhbat',
                'verbose_name_plural': 'AI suhbatlar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'Tizim'), ('user', 'Foydalanuvchi'), ('assistant', 'AI')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Matn')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='ai_audio/')),
                ('is_audio_message', models.BooleanField(default=False)),
                ('detected_intent', models.CharField(blank=True, default='', max_length=50)),
                ('intent_confidence', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'AI xabar',
                'verbose_name_plural': 'AI xabarlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('DAILY_SUMMARY', 'Kunlik hisobot'), ('WEEKLY_SUMMARY', 'Haftalik hisobot'), ('MONTHLY_SUMMARY', 'Oylik hisobot'), ('TASK_ANALYSIS', 'Topshiriq tahlili'), ('CUSTOM', 'Maxsus hisobot')], max_length=30, verbose_name='Hisobot turi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('summary', models.TextField(verbose_name='Qisqacha mazmun')),
                ('content', models.JSONField(default=dict, verbose_name="To'liq mazmun")),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI hisobot',
                'verbose_name_plural': 'AI hisobotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITaskMonitor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rta"), ('HIGH', 'Yuqori'), ('CRITICAL', 'Kritik')], default='LOW', max_length=20)),
                ('needs_attention', models.BooleanField(default=False)),
                ('ai_notes', models.TextField(blank=True, default='')),
                ('warning_sent', models.BooleanField(default=False)),
                ('warning_sent_at', models.DateTimeField(blank=True, null=True)),
                ('comments_analyzed', models.BooleanField(default=False)),
                ('comments_analysis_result', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'AI topshiriq monitoring',
                'verbose_name_plural': 'AI topshiriq monitoringlari',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('system_name', models.CharField(default='E-Hokimiyat Platformasi', max_length=255, verbose_name='Tizim nomi')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name="Texnik xizmat ko'rsatish rejimi")),
                ('welcome_message', models.TextField(blank=True, verbose_name='Xush kelibsiz xabari')),
                ('footer_text', models.CharField(blank=True, default='© 2026 E-Hokimiyat', max_length=255, verbose_name='Footer matni')),
                ('max_upload_size_mb', models.IntegerField(default=10, verbose_name='Maksimal yuklash hajmi (MB)')),
                ('allowed_file_types', models.CharField(default='.pdf,.doc,.docx,.xls,.xlsx,.jpg,.png', help_text='Vergul bilan ajratilgan kengaytmalar', max_length=255, verbose_name='Ruxsat etilgan fayl turlari')),
            ],
            options={
                'verbose_name': 'Tizim Sozlamalari',
                'verbose_name_plural': 'Tizim Sozlamalari',
            },
        ),
    ]
