# Generated by Django 5.2.10 on 2026-01-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('system_name', models.CharField(default='E-Hokimiyat Platformasi', max_length=255, verbose_name='Tizim nomi')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name="Texnik xizmat ko'rsatish rejimi")),
                ('welcome_message', models.TextField(blank=True, verbose_name='Xush kelibsiz xabari')),
                ('footer_text', models.CharField(blank=True, default='© 2026 E-Hokimiyat', max_length=255, verbose_name='Footer matni')),
                ('max_upload_size_mb', models.IntegerField(default=10, verbose_name='Maksimal yuklash hajmi (MB)')),
                ('allowed_file_types', models.CharField(default='.pdf,.doc,.docx,.xls,.xlsx,.jpg,.png', help_text='Vergul bilan ajratilgan kengaytmalar', max_length=255, verbose_name='Ruxsat etilgan fayl turlari')),
            ],
            options={
                'verbose_name': 'Tizim Sozlamalari',
                'verbose_name_plural': 'Tizim Sozlamalari',
            },
        ),
    ]
