# Generated by Django 5.2.10 on 2026-02-01 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tasks', '0004_alter_task_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Suhbat sarlavhasi')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('COMPLETED', 'Yakunlangan'), ('ARCHIVED', 'Arxivlangan')], default='ACTIVE', max_length=20, verbose_name='Holat')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Kontekst')),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'AI suhbat',
                'verbose_name_plural': 'AI suhbatlar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATE_TASK', 'Topshiriq yaratish'), ('CLOSE_TASK', 'Topshiriqni yopish'), ('REMOVE_CONTROL', 'Nazoratdan yechish'), ('GENERATE_REPORT', 'Hisobot yaratish'), ('SEND_NOTIFICATION', 'Bildirishnoma yuborish'), ('CLOSE_APPEAL', 'Murojaatni yopish')], max_length=30, verbose_name='Harakat turi')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('IN_PROGRESS', 'Bajarilmoqda'), ('COMPLETED', 'Bajarildi'), ('FAILED', 'Xato'), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=20, verbose_name='Holat')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parametrlar')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Natija')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_actions', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='core.aiconversation')),
            ],
            options={
                'verbose_name': 'AI harakat',
                'verbose_name_plural': 'AI harakatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'Tizim'), ('user', 'Foydalanuvchi'), ('assistant', 'AI')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Matn')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='ai_audio/')),
                ('is_audio_message', models.BooleanField(default=False)),
                ('detected_intent', models.CharField(blank=True, default='', max_length=50)),
                ('intent_confidence', models.FloatField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.aiconversation')),
            ],
            options={
                'verbose_name': 'AI xabar',
                'verbose_name_plural': 'AI xabarlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('DAILY_SUMMARY', 'Kunlik hisobot'), ('WEEKLY_SUMMARY', 'Haftalik hisobot'), ('MONTHLY_SUMMARY', 'Oylik hisobot'), ('TASK_ANALYSIS', 'Topshiriq tahlili'), ('CUSTOM', 'Maxsus hisobot')], max_length=30, verbose_name='Hisobot turi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('summary', models.TextField(verbose_name='Qisqacha mazmun')),
                ('content', models.JSONField(default=dict, verbose_name="To'liq mazmun")),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.aiconversation')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI hisobot',
                'verbose_name_plural': 'AI hisobotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITaskMonitor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rta"), ('HIGH', 'Yuqori'), ('CRITICAL', 'Kritik')], default='LOW', max_length=20)),
                ('needs_attention', models.BooleanField(default=False)),
                ('ai_notes', models.TextField(blank=True, default='')),
                ('warning_sent', models.BooleanField(default=False)),
                ('warning_sent_at', models.DateTimeField(blank=True, null=True)),
                ('comments_analyzed', models.BooleanField(default=False)),
                ('comments_analysis_result', models.JSONField(blank=True, default=dict)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_monitor', to='tasks.task')),
            ],
            options={
                'verbose_name': 'AI topshiriq monitoring',
                'verbose_name_plural': 'AI topshiriq monitoringlari',
            },
        ),
    ]
