# Generated by Django 5.2.10 on 2026-02-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aiconversation_aiaction_aimessage_aireport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiaction',
            name='action_type',
            field=models.CharField(choices=[('CREATE_RECURRING_TASK', 'Takrorlanuvchi topshiriq yaratish'), ('EXPORT_ANALYTICS', 'Analitika faylini yaratish'), ('CREATE_TASK', 'Topshiriq yaratish'), ('CLOSE_TASK', 'Topshiriqni yopish'), ('REMOVE_CONTROL', 'Nazoratdan yechish'), ('GENERATE_REPORT', 'Hisobot yaratish'), ('SEND_NOTIFICATION', 'Bildirishnoma yuborish'), ('CLOSE_APPEAL', 'Murojaatni yopish')], max_length=30, verbose_name='Harakat turi'),
        ),
    ]
